# Generated by Django 5.2.6 on 2025-09-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='importante',
            field=models.BooleanField(default=False),
        ),
    ]
